workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.veronica.NutreTuBienestar
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Capacitor sync
        script: |
          npm run build
          npx cap sync ios
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.veronica.NutreTuBienestar \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - stephane.delrez@gmail.com